import type { Metadata } from "next";
import localFont from "next/font/local";
import TonTgWallet from "src/providers/TonTgWallet";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <TonTgWallet>
                    {children}
                </TonTgWallet>
            </body>
        </html>
    );
}
